### ISSUE TITLE
Started a new season and was not allowed to build any buildings or towers

### ISSUE THREAD

**Issue by dsabella84** [Memori-Studios/CastlesOnClouds-Playtest#98]
### Current Behavior

Started a new season, and when attempting to create new towers all towers were disabled.
![image](https://github.com/user-attachments/assets/abd60a26-87e2-4c72-b28f-8917ffaa92a5)

### Expected Behavior

Allowed to build towers when starting a new season

### Steps To Reproduce

Not sure how to reproduce and didnt grab the seed number

### Playtest Version (center top)

v0.0.3

### Seed (copy button center top)

0

### Environment Specs

- OS: [eg. Windows 10]
- GPU: [eg. Nvidia RTX 3080]
- CPU: [eg. i7]
- RAM: [eg. 32 Gigs]

**Comment by Memori-Studios** [comment]
Hey man, trying to reproduce. Did you play a previous season and then go back to title then start a new season? And does restarting the game fix it?

**Comment by dsabella84** [comment]
It was weird so I quit out during a season play, came back in to start a
new game and it got into this state.  I was able to resolve by clearing
data out.  Must be something with the save state.  If there is a next time,
what files should  I grab for you?

**Comment by Memori-Studios** [comment]
Appreciate the detailed response. I pushed a change so that reset game button no longer erases the metaprogression points and unlocks, but yeah it was definitely something weird with the save data likely due to me fixing the windmill thing. Apologies that it happened, next time its C:\Users\<You>\AppData\LocalLow\Memori Studios\Castles on Clouds\saveData.json

**Comment by dsabella84** [comment]
Awesome thanks for the update, only lost 3 points of progression so no worries there.
